[project]
name = "secure-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "authlib>=1.5.2",
    "psycopg2-binary>=2.9.10",
    "streamlit>=1.44.1",
]
