

[auth]
redirect_uri="http://localhost:8501/oauth2callback"
cookie_secret="a8f7c3d2e9b1f4a6c5d7e8f9g0h1i2j3"

[auth.auth0]
domain="dev-myiscsydvaxoolul.us.auth0.com"
client_id="mvjKAyqv4CnaGNIHxOHZRHIa2yrH1AUb"
client_secret="1PEIP6Tdepgo5lMZAvceABtXwTBZyd3-Sv3xZDrfH2g6eDRLJYTuwNtdnmatM1vQ"
server_metadata_url="https://dev-myiscsydvaxoolul.us.auth0.com/.well-known/openid-configuration"
client_kwargs = {"prompt" = "login"}